### ISSUE TITLE
Put together a list of Corporate Overlords + Contact Information

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/corporate#26]
Everyone should know everyone's:

1) Name
2) Address
3) Email
4) Phone number
5) Twitter handle
6) Github ID

**Comment by slifty** [comment]
@katedarling I'm gonna start a spreadsheet in the Drive; I know you've been collecting twitter handles, can you add those?

**Comment by katedarling** [comment]
Yup

**Comment by slifty** [comment]
The spreadsheet exists, though nobody knows this for sure since it's private and stuff.
