### ISSUE TITLE
OVERENGINEERED DIPLOMACY Project Application

### ISSUE THREAD

**Issue by louh** [BadIdeaFactory/corporate#37]
# BIFFUD Project Application
As described in section 11.11.B of the BIFFUD Corporate Bylaws I hereby invoke my rights as a sentient being who has not uploaded their mind to the cloud for consideration of this project application by the BIFFUD Hive Mind.  With this application I submit my interest in ~~becoming a Member of BIFFUD and~~ having this project supported and adored by all who can 🤔.

## Project Information
- Project Name: Overengineered Diplomacy
- Project Haiku: 
```
this line does not have
five syllables. the next has
seven syllables
```
- Project Analogy: It's like Civilization V for Diplomacy

### Project Description

Original description:

> A few of us decided to play diplomacy over Slack... then we decided to build things to delay and publicize the friend-death.

> Diplomacy is a game that breaks people. It involves betreyal and backstabbing over a long period of time. The premise is simple: the players are all world powers and they control armies. Each power wants to control as much territory as possible. All moves are deterministic, there is no randomness to the game. However, people can lie about what they plan to do.

> Playing diplomacy is a bad idea in itself, but writing complex code to publicly render an otherwise private, simple game is a genuine waste of raw creative energy.

via https://github.com/BadIdeaFactory/overengineered-diplomacy

### How is this project a bad idea?

We tried to do this a year ago and everything got sidetracked when Russia engineered a coup in the United States in a completely unrelated, different game.

### If this project were a D&D Character, what alignment would it be and why?
Alignment:
- [ ] [Chaotic Good](http://easydamus.com/chaoticgood.html)
- [x] [Neutral Good](http://easydamus.com/neutralgood.html)
- [ ] [Chaotic Neutral](http://easydamus.com/chaoticneutral.html)
- [x] Neutral Awesome

### Where are the lulz?

It's imperative for the game board to be exportable as a GIS layer, dammit.

### How does this project make people thinking face emoji?

You have to think a lot to play.

### Who is involved?

- Name: Lou Huang
- Twitter: @saikofish
- Github ID: @louh
- Skillz: JavaScript, UI, maps, Redis-backed Node.js game engines
- Project role / expectations: I'll start from here and work outwards https://github.com/louh/diplomacy-map
- Project stake: X% ownership of the project

Pinging @slifty @knowtheory @crupar do you still want to be involved?

### Who will be the project's Comptroller?

I can do it, I got visionz

### Is this realistic to implement via BIFFUD?

We certainly thought so before BIFFUD was a thing

## Next Steps
Please attend the next scheduled BIFFUD plotting session to plead your case.
This issue will be updated with application status and next steps.

**Comment by slifty** [comment]
(Count me in!)
Name: Dan Schultz
Twitter: @slifty
Github ID: @slifty
Skillz: overcommitting, javascript, CSS, backend too
Project role / expectations: I'll help out where I can; just assign me tasks!
Project stake: up to Lou!
