### ISSUE TITLE
THE EMOJI COMPASS Project Application

### ISSUE THREAD

**Issue by mstem** [BadIdeaFactory/corporate#45]
# BIFFUD Project Application

As described in section 11.11.B of the BIFFUD Corporate Bylaws I hereby invoke my rights as a sentient being who has not uploaded their mind to the cloud for consideration of this project application by the BIFFUD Hive Mind. With this application I submit my interest in becoming a Member of BIFFUD and having this project supported and adored by all who can 🤔.

## Project Information

Project Name: The Emoji Compass
Project Haiku: 

You ask the compass,
"How am I going to die?"
It answers, "🦉🍞."

Project Analogy: It's like an emoji Magic 8 ball for people who read the His Dark Materials trilogy

### Project Description

The Dark Materials trilogy is centered around a "Golden Compass". Its official name is alethiometer, or "truth measure". The device is like a compass, in that it's the size of a pocketwatch and has needles that spin toward answers. Its face shows 36 symbols, each of which can represent 12+ ideas, concepts, or literal meanings. 

To use the compass, the user sets the three needles to three symbols that frame the question she is posing, and then the alethiometer spins the needles to three symbols to provide a cryptic answer. This answer is truth, but must be carefully interpreted. 

I would like to create a mobile app that replaces the 36 alethiometer symbols with emoji. The answers the app returns to users' queries will be almost completely random, but shrouded in the symbology of the novels, it'll be really hard to prove that.

There's an emoji equivalent for each symbol on the compass. (Twitter's open sourced emoji collection may do it, but is two years out of date, so we may need to purchase the license to use Emoji One's updated collection).

### How is this project a bad idea?

This project takes a beloved fantasy novel's central artifact and makes light of it with inane emojis. Furthermore, the logic behind the app's "truth-telling" will be fairly random, potentially opening us up to lawsuits when someone misinterprets their answer and does something stupid.

### If this project were a D&D Character, what alignment would it be and why?

Rebel (chaotic good), because it "follows [its] own moral compass, which, although good, may not agree with that of society." Source http://easydamus.com/alignment.html. 

Alignment:

- [x] Chaotic Good
- [ ] Neutral Good
- [ ] Chaotic Neutral

### Where are the lulz?

Fans of the Dark Materials books may actually enjoy having a Golden Compass app to play with, and the emoji symbols correctly set expectations for the nonsense answers we're likely to return. 

### How does this project make people thinking face emoji?

When the user asks the Emoji Compass a serious question, they will be provided a reply with a (unbeknownst to them) random array of emojis. The wide range of potential symbolistic interpretations will allow the user to infer meaning where there was none to begin with, not unlike reading into lyrics to a song, or the punchline of a New Yorker cartoon.

[Don't thinking face emoji too hard]

### Who is involved?

Name: Matt Stempeck
Twitter: @mstem
Github ID: mstem
Skillz: HTML/CSS, making things popular on the internet
Project role / expectations: Ideally, work with a more skilled Corporate Overlord to drive the project to completion, then reach out to the Dark Materials fandom and media to promote the app.
Project stake: 50%

Name: Literally anyone else
Skillz: HTML / CSS / Javascript skills
Project role / expectations: Build out a basic circle of emojis that allow the user to select three, have it spin around a bunch, and then return three other random emojis.
Project stake: %50

### Who will be the project's Comptroller?
Matt

### Is this realistic to implement via BIFFUD?

Yes. This is a very simple app (mobile web app with PhoneGap wrappers). It will let us test the waters on building and launching something quickly. We can license the emoji we need for it.

## Next Steps

Please attend the next scheduled BIFFUD plotting session to plead your case. This issue will be updated with application status and next steps.

BONUS: The 36 Emoji Compass symbols, as represented by emoji. 
🐘
αΩ 
😇
‎ 🐜
‎🍏
‎ 👶
‎🐝
‎🐦
 ‎🍞
 ‎ 🐮
 ‎🐫
 ‎🕯
 ‎🍲
 🦎
 ‎💠
 ‎ ‎🎉
🐊
🐬
⚓
🌐
🦅
⛑️
 🐎
⏳
🎸
🤱
🎎
🌕
🦉
🐍
☀
⚔️
 ⚡
 ‎🌳
🌹
👹

La Belle Sauvage 🛶

(The breastfeeding mother isn't appearing consistently yet but could be replaced by the woman emoji.)

**Comment by louh** [comment]
This looks like a pretty reasonable short term project with some long-term strategic benefits:

- Would we be able to put the app on various app stores?
- If we did so, is there an audience of His Dark Materials fans willing to pay $X.99 for this? (This would be another instance where the application itself is open source and freely obtainable for anyone with Git know-how but the less technically savvy would be just as happy forking over a few bucks for It Just Works After I Press A Button)
- Could the proceeds be enough to pay for BIFFUD-wide Apple/Microsoft developer accounts?

I think EmojiOne licensing might be a little complicated to deal with. The project would need to be open source (as required by [BIFFUD law](https://github.com/BadIdeaFactory/corporate/blob/master/documents/operating.md#intellectual-property--internet-protocol) but the licensed emoji cannot be included in the repository. Also, what are we in their [tier structure](https://www.emojione.com/developers/premium-license)? A small business? A medium business? The difference in fees can be substantial. Since a license can be used in infinite projects per organization with a one-time fee, a license could be obtained as a BIFFUD asset but this would need to be approved by all COs during the plotting session.

Regarding open source emoji, how far behind is it? Between [Twitter emoji](https://github.com/twitter/twemoji) and [EmojiOne v2](https://www.emojione.com/emoji/v2), which emoji are we actually missing? As an alternative, could we use EmojiOne's low-res imagery, which only requires attribution?

**Comment by slifty** [comment]
Love the proposal.

Some thoughts on my end: Investing in emoji seems appropriate for our company.  We have zero employees so I think we would qualify for small business, however I also think that emailing them and explaining the situation might be worth it.

**Comment by mstem** [comment]
Thanks for reading + responding!

We could definitely put the app on app stores. I'm on the fence about $0.99
charge. We'd get a lot more users / buzz if it's free, and as Lou noted,
charging for it also brings up issues with the EmojiOne license but also
our fair use of the Dark Materials alethiometer concept. We can steer well
clear of violating trademarks, but charging for it raises the legal
interpretation bar, right?

I also figured investing a small amount in emoji made sense for BIF, but
didn't want to speak for others. I think an email explaining that we're an
awkward entity of not-really-for-profit creatives wouldn't hurt. I don't
mind doing attribution on projects, if we want to throw that in as a
sweetener. Backup, we can always do individual license.

Lou, I'll compare Twemoji and EmojiOne 3.0 to see which might be missing.

**Comment by slifty** [comment]
I don't know what BIF means, I assume you meant BIFFUD.

**Comment by mstem** [comment]
Yes, that

**Comment by louh** [comment]
Matt -- I think you're right regarding the fair use of Dark Materials -- we can't sell the app commercially.

**Comment by slifty** [comment]
Two words: Freemium

**Comment by louh** [comment]
I think you are missing the first (or last) two lines of that haiku

**Comment by chriszs** [comment]
I like this idea, but worry entering three emojis as input will be a hurdle to the lols. It seems funnier if the user has open-ended agency to give the app their hopes and dreams (possibly by text chat or by fake audio recording?) and gets back three emojis. Text chat in particular opens the potential to do it as a bot, which might help adoption, but I'm not sure if that helps or hurts the lols.
