### ISSUE TITLE
SCRIPTCHAT Project Application

### ISSUE THREAD

**Issue by louh** [BadIdeaFactory/corporate#46]
# BIFFUD Project Application

As described in section 11.11.B of the BIFFUD Corporate Bylaws I hereby invoke my rights as a sentient being who has not uploaded their mind to the cloud for consideration of this project application by the BIFFUD Hive Mind.  With this application I submit my interest in ~~becoming a Member of BIFFUD and~~ having this project supported and adored by all who can 🤔.

## Project Information
- Project Name: Scriptchat
- Project Haiku: 
```
all the world's a stage
and people, merely players
so why not slack too
```
- Project Analogy: It's like a screenwriter for your inane Internet chatter

### Project Description

It takes something like this:

![screenshot 2017-11-16 22 31 58](https://user-images.githubusercontent.com/2553268/32928333-7511f550-cb1f-11e7-877d-923575e35576.png)

And makes it look like this:

![screenshot 2017-11-16 22 44 15](https://user-images.githubusercontent.com/2553268/32928404-c297cb24-cb1f-11e7-802c-335a65eee0bc.png)

On the surface, it looks like a relatively simple reformatting of chat output into a screenplay. However, the adaptation is much more sophisticated: many of the conventions of text chat must be translated, for instance, emoji reactions turn into stage direction. Threads turn into cuts. Timestamps can indicate whether there are long pauses in conversation or if many people are talking over each other. And if we can know how long someone takes to type a thing, it can be translated into something like `CHARACTER is trying to formulate the words carefully.`

### How is this project a bad idea?

It isn't. But I shopped it around to a lot of different producers and they all passed on it, so I need BIFFUD to greenlight this project so that my creative genius is finally recognized by the Academy.

### If this project were a D&D Character, what alignment would it be and why?

Alignment:
- [x] [Chaotic Good](http://easydamus.com/chaoticgood.html)
- [ ] [Neutral Good](http://easydamus.com/neutralgood.html)
- [ ] [Chaotic Neutral](http://easydamus.com/chaoticneutral.html)

### Where are the lulz?

When we are able to hire actors to dramatically and emotionally re-enact, on stage, with props and blocking, the words of a bunch of nerds using their computers as a substitute for human interaction.

One application of this application is to enable distributed improv troupes to create hilarious scenes, which can then be showcased later by non-improv actors.

### How does this project make people thinking face emoji?

🤔 

Research suggests that that there is no such thing as a singular "true self" [_citation needed_], and that one's behavior instead subtly transforms when one is placed into different contexts, for various reasons, such as the desire to be accepted by a social group, or to attain status in one context but to remain unnoticed in another [_citation needed_]. When observing a person interacting with a particular social group, physical and behavioral cues, including posture, location and proximity to other persons, speech patterns, volume, gestures, and other interpersonal dynamics are signs of the role that this person plays within this group [_citation needed_]. As such, all real-life interaction are inherently performative  [_citation needed_]. Yet, when these cues are stripped away, as in the case of a text-only medium like Internet chat, one's intended intonation and voice are obscured, and indeed the speaker is stripped of personality and performance [_citation needed_]. By interpreting the subtle cues that may be present in the act of typing itself, physical cues can be translated into stage direction for later re-enactment [_citation needed_]. Yet the multitudes of differing adaptions of the textual content of a play lends itself to a rich tapestry of interpretation, reminding us that all text, and perhaps even all physical and behavioral cues, are filtered through many lenses including that of the viewer, such that the "true self" of the original speaker may remain completely unknowable [_citation needed_].

### Who is involved?

- Name: Lou Huang
- Twitter: @saikofish
- Github ID: @louh
- Skillz: front-end / design / product
- Project role / expectations: team captain
- Project stake: 1000% ownership of the project

...*and you!*

### Who will be the project's Comptroller?

https://www.youtube.com/watch?v=1EnWG8PpHco&feature=youtu.be&t=1m11s

### Is this realistic to implement via BIFFUD?

...*sure*

## Next Steps

Please attend the next scheduled BIFFUD plotting session to plead your case.
This issue will be updated with application status and next steps.

**Comment by riordan** [comment]
I only support this project if it can be used to create Xtranormal videos.
![https://media.npr.org/assets/artslife/arts/2011/01/iphone-337e2e033a3510333dd903f427d82a53120d5fcc-s300-c85.jpg](Screenshot from Xtranormal)

This may be challenging as Xtranormal shut down in 2013.

**Comment by mstem** [comment]
This is a beautiful concept. Has there been a leak of a Slack chat
transcript of societal importance yet? Like all those journalist listservs?
Because in that case I'm pretty sure hiring actors makes this project
eligible for funding from Foundations of the Arts.

**Comment by slifty** [comment]
I just wanted to say that this application is a piece of art and exactly the kind of project I think belongs in BIFFUD.  Also, this will go a LONG way towards our vision of pitching NBC on a GPF sitcom.

**Comment by chriszs** [comment]
Obviously we have to act one of these out at FUDCON.

**Comment by reefdog** [comment]
(Bah, *Fountain*, not Foundation. Been working in Foundation lately and mistyped.)

**Comment by louh** [comment]
👍 to Fountain! I'm glad there's an open and gracefully-degrading format already in existence; that's awesome.
