### ISSUE TITLE
dedox Project Application

### ISSUE THREAD

**Issue by jeremybmerrill** [BadIdeaFactory/corporate#48]
# BIFFUD Project Application
As described in section 11.11.B of the BIFFUD Corporate Bylaws I hereby invoke
my rights as a sentient being who has not uploaded their mind to the cloud for consideration of this project application by the BIFFUD Hive Mind.  With this
application I submit my interest in becoming a Member of BIFFUD and having this
project supported and adored by all who can 🤔.

## Project Information
- Project Name: dedox
- Project Haiku that misleadingly begins in Limerick format: `there once was a man / who lived at a pizza hut / i read it online`
- Project Analogy: `It's like Spokeo but for imaginary doppelgangers of people who get doxxed`

### Project Description
it sucks when people get doxxed; this application will dedox them by creating twitter accounts (and maybe websites like Spokeo and Pipl?) that also doxx them, but with fake details. I mean, not fake-fake details, but the details (phone, address, etc.) of a widespread :pizza: restaurant that [describes itself as serving restaurant quality food](http://restaurantquality.pizzahut.com/).

it's kinda like a cloud of chaff _but for the 'net_.

### How is this project a bad idea?
have you ever seen The Watchmen? I haven't, but I assume the movie grapples with tough ethical questions regarding recursion: once you answer _quis ipsos custodes custodet_ with "the watchmen" you then have to ask _quis *ipsos custodes-custodes* custodet_ and then _quis ipsos_... forever and ever. Who dedoxxes the dedoxxers? the consequences are unknowable, but, you know, we have to face our future. it's inevitable.

### If this project were a D&D Character, what alignment would it be and why?
Alignment:
- [ ] [Chaotic Good](http://easydamus.com/chaoticgood.html)
- [ ] [Neutral Good](http://easydamus.com/neutralgood.html)
- [x] [Chaotic Neutral](http://easydamus.com/chaoticneutral.html)

### Where are the lulz?
no one lives at Pizza Hut!

### How does this project make people thinking face emoji?
it's basically phonebook section of the Library of Borges.

### Who is involved?
- Name: Jeremy Merrill
- Twitter: @jeremybmerrill
- Github ID: jeremybmerrill
- Skillz: comptooters
- Project role / expectations: backend or whatever
- Project stake: 1 / count(members)

- Name: Dan Schultz
- Twitter: @slifty
- Github ID: slifty
- Skillz: comptooters
- Project role / expectations: twitter bot
- Project stake: 1 / count(members)

### Who will be the project's Comptroller?
@slifty is going to be Computer Trolling this project.

### Is this realistic to implement via BIFFUD?
uhh, yeah, it's a twitter bot

## Next Steps
Please attend the next scheduled BIFFUD plotting session to plead your case.
This issue will be updated with application status and next steps.

**Comment by slifty** [comment]
This proposal is excellent and amusing, however this project did not get approval -- the Hive Mind raised some very valid concerns around whether folks who have been doxed would actually appreciate fake doxes (vs being made even more uncomfortable)

Similarly, linking to pizza hut locations in the context of a dox could still lead to real humans being harassed.  There was a good idea on this regard of using known [trap streets](https://en.wikipedia.org/wiki/Trap_street) from old maps.

I spoke with Jeremy and for now we are going to close this application.
