### ISSUE TITLE
BIFFUD Style Guide

### ISSUE THREAD

**Issue by ijanderso** [BadIdeaFactory/corporate#51]
okay, so we have a style guide in progress, but critically we want to be able to have the horizon for the logo change as a function of the time of day that the document is accessed/printed/etc. Is this possible?

**Comment by DylanMoriarty** [comment]
Fan of BIF. 

[Sure is!](https://www.w3schools.com/jsref/jsref_obj_date.asp) 🌔

**Comment by slifty** [comment]
Good news everyone

```vbscript
Sub TruHorizon™()
'
' TruHorizon™ Macro
' Rotate the BIFFUD Logo based on time of day
'
    Dim i As Long
    Dim time As Integer
    Dim rotation As Long
    
    time = Hour(Now) * 60 + Minute(Now)
    rotation = time / 1440 * 360
    For i = 1 To ActiveDocument.Shapes.Count
        Dim convertedShape As Shape
        ActiveDocument.Shapes(i).rotation = rotation
    Next i

    Application.OnTime Now + TimeValue("00:00:10"), "TruHorizon™"
End Sub
```

**Comment by slifty** [comment]
I have mixed emotions about the fact that our letterhead is far more professional now, but, still, I do have to close this since WE HAVE A WEBSITE AND BRAND
