### ISSUE TITLE
SIGNATURE EFFECTS Project Application

### ISSUE THREAD

**Issue by amccartney** [BadIdeaFactory/corporate#55]
# BIFFUD Project Application
As described in section 11.11.B of the BIFFUD Corporate Bylaws I hereby invoke my rights as a sentient being who has not uploaded their mind to the cloud for consideration of this project application by the BIFFUD Hive Mind.  With this application I submit my interest in becoming a Member of BIFFUD and having this project supported and adored by all who can 🤔.

## Project Information
- Project Name: Signature Effects
- Project Haiku:

<img width="697" alt="screen shot 2017-12-17 at 9 19 17 am" src="https://user-images.githubusercontent.com/3728486/34082002-664dfeca-e30b-11e7-87d0-98f1bbcd44f4.png">

- Project Analogy: It's like Microsoft Word Art, but with signatures

### Project Description

Boring
![original_djt_signature](https://user-images.githubusercontent.com/3728486/34081858-1d4a212e-e309-11e7-956a-9a596e9c8869.png)

Not boring
![word_art_signatures](https://user-images.githubusercontent.com/3728486/34081856-1a1e5506-e309-11e7-8058-2db208c1c3be.png)

### How is this project a bad idea?
Hopefully people will use this to sign BIFFUD legal documents, which is probably a bad idea. 

### If this project were a D&D Character, what alignment would it be and why?
Alignment:
- [ ] [Chaotic Good](http://easydamus.com/chaoticgood.html)
- [ ] [Neutral Good](http://easydamus.com/neutralgood.html)
- [x] [Chaotic Neutral](http://easydamus.com/chaoticneutral.html)

Don't know? [This might help](https://www.google.com/search?q=D%26D+alignment+tables)

### Where are the lulz?
<img width="478" alt="screen shot 2017-12-17 at 9 14 33 am" src="https://user-images.githubusercontent.com/3728486/34081954-c0ad8508-e30a-11e7-91fc-27d048c8cd19.png">

### How does this project make people thinking face emoji?
<img width="466" alt="screen shot 2017-12-17 at 9 26 18 am" src="https://user-images.githubusercontent.com/3728486/34082070-649c224a-e30c-11e7-8507-a1703aff6405.png">

### Who is involved?
[For each member...]
- Name: Allison McCartney
- Twitter: @anmccartney
- Github ID: @amccartney
- Skillz: Web design/development, an intimate knowledge and appreciation for the Original Microsoft Word Art
- Project role / expectations: Project manager, developer
- Project stake: 100%

_But folks who know canvas, please come!_

### Who will be the project's Comptroller?
Allison McCartney

### Is this realistic to implement via BIFFUD?
Quite

## Next Steps
Please attend the next scheduled BIFFUD plotting session to plead your case.
This issue will be updated with application status and next steps.

**Comment by louh** [comment]
## Endorsement

"I would rather use Signature Effects(TM) over the ridiculous handwriting font in Docusign!" -- Lou Huang
