### ISSUE TITLE
BuyTime Project Application

### ISSUE THREAD

**Issue by erekalper** [BadIdeaFactory/corporate#57]
# BIFFUD Project Application
As described in section 11.11.B of the BIFFUD Corporate Bylaws I (we) hereby invoke my (our) rights as a (~~a~~) sentient being(s) who has (have) not uploaded their mind(s) to the cloud for consideration of this project application by the BIFFUD Hive Mind.  With this application I (we) submit my (our) interest in becoming a (~~a~~) Member(s) of BIFFUD and having this project supported and adored by all who can 🤔.

#### ... For the Overmind.
- Project Name: BuyTime
- Project Haiku:

> Time is linear
> But in case it's cyclical
> You'd better buy some

- Project Analogy: It's like eBay for time. Or maybe Amazon. Definitely not Uber. Unless...

  No.

### Project Description
BuyTime will be a website in which one can buy periods of time, much in the same way that one can name a star.

The idea came about over high school lunch table discussions about a commodity we could sell without having to produce anything tangible (other than, perhaps, a certificate of sale). It's beyond snake oil; in buying it, one inherently knows one is not actually getting anything "real". Which sounds beyond stupid, but there are plenty of examples out there: [canned air](http://www.airofjerusalem.com/) from various locations, [naming rights to stars](https://osr.org/), [land on celestial objects](https://www.lunarland.com/), [bottled water](http://www.aquafina.com) in first world countries... you get the idea. So we had a brainstorm (it was a bad one; we had to put our tongue guards in) and came up with: time.

As @bluxenberg put down in a later recap of the initial lunch table discussions:

> After doing some initial research, we learned that, for example, 1/6 of Israelis had purchased land on the moon. Giving land on the moon had become a popular funny gift in the country. After learning about the moon land sales, we spent time generating ideas about similar things we could sell. The key characteristic was there could be no accountability for what we were selling. That is, no one could ever claim you sold them something faulty, defective, or, at base, anything material beyond a piece of paper. We identified selling time as the perfect commodity that could meet the core characteristic of no accountability.

In terms of how time would be sold, we came up with a few initial ideas:

- **Direct**. Sell individual blocks of time directly. The value of blocks might vary depending on when they occurred.
- **Auctions**. Let people bid up the price of individual periods of time.
- **Shares**. Allow people to own a "share" of a particular time block. We could cap the number of shares at some artificial number in order to create false market scarcity. E.g., you could own five shares of your birthday or one share of the day of Pearl Harbor.
- **Secondary Markets**. Resale market where people could sell and trade the time blocks or shares that they own. We would take a cut of each transaction. BLOCKCHAIN!?

No matter what kind of sale, there should be a digital certificate associated with it. Thankfully, BIFFUD has already developed/is developing awful technology for memos and signatures. A physical version could be mailed for a price.

There are many open questions about implementation here. A big one that comes to mind is futures: do we do 'em? But we're excited to discuss everything with the Hive Mind.

### How is this project a bad idea?
We're selling nothing. People will either give us money for nothing, which is bad, or we'll have wasted a ton of time, which is bad.
Bad.
Bad bad bad.

And yet, as Erek just described the project to his wife, her eyes went wide and she asked if she could be the first person to buy a few dates.

So... is it bad if it makes someone happy? What a perfect segue to...

### If this project were a D&D Character, what alignment would it be and why?
Alignment:
- [ ] [Chaotic Good](http://easydamus.com/chaoticgood.html)
- [x] [Neutral Good](http://easydamus.com/neutralgood.html)
- [ ] [Chaotic Neutral](http://easydamus.com/chaoticneutral.html)

As the above link says about neutral good, "it advances mediocrity by limiting the actions of the truly capable." What a perfect summation of this project.

### Where are the lulz?
We hold these lulz to be self-evident.

### How does this project make people thinking face emoji?
[Don't thinking face emoji too hard] <- you're not our boss, advisory sentence.

According to the Wikipedia article on the [labor theory of property](https://en.wikipedia.org/wiki/Labor_theory_of_property):

> In his Second Treatise on Government, the philosopher John Locke asked by what right an individual can claim to own one part of the world, when, according to the Bible, God gave the world to all humanity in common. He answered that persons own themselves and therefore their own labor. When a person works, that labor enters into the object. Thus, the object becomes the property of that person.

However, according to a [highDEAS post](http://highdeas.com/philosophy/How_can_someone_own_land) submitted by kit on May 11, 2010:

> It doesn't make sense that people can own parts of the Earth. It's weird that some people a long time ago just looked at the land and was like I call this one, this is mine. It'd be like someone owning the ocean or a part of it. It's kinda fucked up.

So as you can see, two opposing arguments made by titans of philosophy. If that doesn't make you 🤔, you're dead inside. Or not high enough.

### Who is involved?
In no particular order:

**Sentient Being**
- Name: Erek Alper
- Twitter: [@erekalper](https://twitter.com/erekalper)
- Github ID: @erekalper
- Skillz: Moderate front- and back-end.
- Project role / expectations: Setting everything up initially. Seeking help with online sales, etc. that he's not worked on before. Also basically anyone with an actual eye for aesthetics.
- Project stake: 50% (or less, if others want to come on)

**Sentient Being**
- Name: Ben Luxenberg
- Twitter: [@BenLuxenberg1](https://twitter.com/BenLuxenberg1)
- Github ID: @bluxenberg 
- Skillz: Has an MBA. Marketing, #moneystuff, etc.
- Project role / expectations: Ideas, helping with design, being official about real-world stuff. Again, he's got an MBA.
- Project stake: 50% (or less, if others want to come on)

**Sentient Being**
- Name: YOU!?
- Twitter: @YOU!?
- Github ID: @YOU!?
- Skillz: Front-end, back-end, design, sales, etc. Basically anything!
- Project role / expectations: Being a partner and helping out with your area(s) of expertise.
- Project stake: Even split.

### Who will be the project's Comptroller?
Ben Luxenberg. It really can't be stressed enough that he has an MBA.

### Is this realistic to implement via BIFFUD?
Hell yes.

## Next Steps
Please attend the next scheduled BIFFUD plotting session to plead your case.
This issue will be updated with application status and next steps.

**Comment by slifty** [comment]
Just wanted to note that I am going to have trouble supporting this proposal with the haiku as written.

**Comment by knowtheory** [comment]
@slifty on what grounds?  The haiku scans properly.  Are you taking issue with the content?

**Comment by erekalper** [comment]
Oh he's 100% taking issue with the fact that time is linear. I might've even written it for that reason alone.

**Comment by slifty** [comment]
Yes. Erek knows what he did.
