### ISSUE TITLE
2018-01-05 Admistrivia Tower Defense

### ISSUE THREAD

**Issue by knowtheory** [BadIdeaFactory/corporate#58]
OKAY ROUND ONE

@slifty & @knowtheory try and get issues done to further the BIFFUD agenda.

BRING ON YOUR ISSUES.

**Comment by knowtheory** [comment]
Oh, the time limit is 1 hour, and it starts 10 minutes ago at Noon Eastern Time

**Comment by knowtheory** [comment]
- [ ] Computing credits (AWS?, GCP? Azure?)
- [ ] Status of Taxes
- [ ] Revise Project template
- [ ] Git tutorial

**Comment by slifty** [comment]
- Working on the website

**Comment by knowtheory** [comment]
- [ ] renew registration for biffud.com

**Comment by slifty** [comment]
- [ ] Clean up corporate repository
- [ ] Compile visual assets
- [ ] Document social accounts / links / online presences in wiki

**Comment by slifty** [comment]
- [ ] Set up a corporate calendar

**Comment by slifty** [comment]
- [ ] buying the gavels

**Comment by knowtheory** [comment]
- [ ] Sketch out a project proposal approval starter kit for interfacing with BIFFUD.
- [ ] Sketch out a "How can i help BIFFUD" document for Overlords, members & helpful randos

**Comment by slifty** [comment]
- [ ] Offer / buying letter to Tronc
- [ ] What3emoji acquisition strategy.

**Comment by knowtheory** [comment]
OKAY TIME LIMIT IS UP.

I checked off two things, and we added a whole bunch of todos.
