### ISSUE TITLE
ELECTIONS 2018

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/corporate#67]
If you are a Corporate Overlord interested in applying for an Elected Overlord position, this is the issue thread for you.

To apply for a position simply [copy this markdown](https://raw.githubusercontent.com/BadIdeaFactory/corporate/master/ISSUE_TEMPLATE/elected_issue_template.md) and fill it out with your information as a comment in this thread.

Elections will be held during May's plotting session (since April's is too soon and would violate the 24 hour bylaws clause).

**Comment by slifty** [comment]
## Who are you?
Dan Schultz

## What position are you running for? (Choose one)
Overmind

## Why are you qualified?
I am the only person who has ever held this position in the history of the human race.
I also know all the passwords and refuse to ever give them up.

## What is your favorite color?
Still green

## What do you think this position should involve?
The bylaws lay out a few responsibilities, but ultimately BIFFUD is in its infancy and every role -- including this one -- is still taking shape.  As an organization we rely on people being willing to pay attention to what the heck is going on, and ideally put some time into keeping things moving.

I think it is the job of the overmind to keep things interesting enough for that to continue.  It's also the Overmind's job to help us figure out how to ~trick~ inspire people into helping smooth out the kinks and streamline our processes.

## Is there anything you would do differently than the last schlub to do this?
I would like to work more closely with other elected overlords to nail down what their roles actually mean, and try to help empower other people to contribute in ways they find entertaining and productive.

## What are your goals for your tenure, how will you make 'em happen?
This is... this is the same thing as the previous question right?  Who the hell wrote this form.

Oh I get it the previous one was more about throwing shade at the incumbent!  This makes sense now.

## You don't get paid for this, what is wrong with you?
Lulz are the only payment I require to survive.

That said, I actually see real opportunity in Bad Idea Factory -- which is really weird.  We're a group of amazing people who are willing to pay attention to a weird thing; and the rest of the world assumes that companies are credible.

The system feeds into itself, it's amazing!

## When you lose the election, how will you want to stay involved?
I would focus more of my BIFFUD energy on building projects.  I hope I can really do that some day.

## Any last words?
Donald Trump is president of the United States.

**Comment by maboa** [comment]
## Who are you?
Mark of Boas

## What position are you running for?
Bea(s)tmaster

## Why are you qualified?
Let him who hath understanding reckon the number of the Beast 

## What is your favourite colour?
beige

## What do you think this position should involve?
Dourness, condescension and wrath.

## Is there anything you would do differently than the last schlub to do this?
I am the last schlub, you schlub!

## What are your goals for your tenure, how will you make 'em happen?
I'll be more beastly. I'll also be more tuned to the beat of all BIFFUD's projects. Introducing rhythm to an organisation with two left feet. Hence Bea(s)tmaster. (This all came out of an initial typo - but I'm rolling with it).

This will involve more regular engagement with project owners.

## You don't get paid for this, what is wrong with you?
Beastliness is a way of life. Also proud to be part of the whimsical resistance.


## When you lose the election, how will you want to stay involved?
By pouring more scorn.

## Any last words?
Yes.

**Comment by chriszs** [comment]
## Who are you?
Mike Tigas

## What position are you running for?
Undermind

## Why are you qualified?
I run ops for ProPublica. Have you seen all the websites we maintain? It's a lot!

## What is your favorite color?
Probably fuschia?

## What do you think this position should involve?
Trolling Dan

## Is there anything you would do differently than the last schlub to do this?
Not run DocumentCloud.

## What are your goals for your tenure, how will you make 'em happen?
🤔

## You don't get paid for this, what is wrong with you?
Somebody forged my application

## When you lose the election, how will you want to stay involved?
Still trolling

## Any last words?
No.

**Comment by katedarling** [comment]
## Who are you?

Kate Darling

## What position are you running for? (Choose one)

The Popular One

## Why are you qualified?

I've only made typos and mistakes in about every other BIFFUD tweet. Also Rivers Cuomo tweeted that I'm dope.

## What is your favorite color?

Chartreuse. Well, the liquor.

## What do you think this position should involve?

Wearing a sparkly crown!!!

## Is there anything you would do differently than the last schlub to do this?

No, the last person was PERFECT.

## What are your goals for your tenure, how will you make 'em happen?

Tweet more consistently, help build out presence on other social media, trick more bots into following us.

## You don't get paid for this, what is wrong with you?

When I told my husband that I hoped to be reelected as The Popular One, he said "You know the social media person is, like, the lowest position" and I said "Roles that bring me joy are actually the highest possible position in life." OH SNAP

## When you lose the election, how will you want to stay involved?

By blocking all of you on Twitter.

## Any last words?

Flint still doesn't have clean water

**Comment by knowtheory** [comment]
## Who are you?

Ted Han

## What position are you running for? (Choose one)
- [ ] Overmind
- [x] Undermind
- [ ] Treasure Goblin
- [ ] Keeper of Lore
- [ ] Secretary of Code
- [ ] Beastmaster
- [ ] The Popular One

## Why are you qualified?

As the most experienced Undermind candidate in this election, i feel that my track record speaks for itself.

My conceptual role model for this position is as stated by Balthazar Melchior from Dark Science

![screen shot 2018-05-18 at 8 06 11 am](https://user-images.githubusercontent.com/192/40242460-999f0042-5a72-11e8-9c5a-afd2d3d615fe.png)
![screen shot 2018-05-18 at 8 06 25 am](https://user-images.githubusercontent.com/192/40242462-9c1bfc8a-5a72-11e8-983b-0be54066fa39.png)

## What is your favorite color?

Still blue.  Although i do like green.

## What do you think this position should involve?

Shadowing and plotting against the Overmind, in preparation to step in after the Overmind's inevitable downfall.

## Is there anything you would do differently than the last schlub to do this?

NO, EVERYTHING HAS BEEN EXCELLENT

## What are your goals for your tenure, how will you make 'em happen?

Onboard more projects.  Get more funding.  Undermine the Overmind.

## You don't get paid for this, what is wrong with you?

It is important to be an agent of chaos.

## When you lose the election, how will you want to stay involved?

Proposing and participating in BIFFUD projects.

## Any last words?

We'll see.

**Comment by crupar** [comment]
## Who are you?
Carolyn Rupar-Han, CDM, RSE, UE 

## What position are you running for? (Choose one)
- [ ] Overmind
- [ ] Undermind
- [ ] Treasure Goblin
- [X] Keeper of Lore
- [ ] Secretary of Code
- [ ] Beastmaster
- [ ] The Popular One

## Why are you qualified?
I'm going to interpret this as [OED's second definition](https://en.oxforddictionaries.com/definition/qualified).
I'm not complete or absolute because I'm a realist and know I will never 'know' everything.	

## What is your favorite color?
Purple

## What do you think this position should involve?
Keeping the Lore- crafting the mythos and origin story of Biffud.  
Recording quotes and other important things.


## Is there anything you would do differently than the last schlub to do this?
I suggest dividing the Keeper of Lore up into two separate roles.  
Or at least automating parts of it....

## What are your goals for your tenure, how will you make 'em happen?
Putting into writing the true Lore of Biffud.  Recording quotes properly.  Helping get the lore onto our website.

## You don't get paid for this, what is wrong with you?
Many, many, many things.

## When you lose the election, how will you want to stay involved?
Lose?  Bah.  
In the words of the worst Iron Fist ever: "I have a vision of total victory and nothing else."

## Any last words?
I never thought I'd quote Danny Rand.  But it seemed somehow fitting...

**Comment by crupar** [comment]
Ugh.  My stupid track pad is not working properly.  Sorry.
