### ISSUE TITLE
[Project Application] 4,000 under 40

### ISSUE THREAD

**Issue by mstem** [BadIdeaFactory/corporate#71]
# BIFFUD Project Application
As described in section 11.11.B of the BIFFUD Corporate Bylaws I (we) hereby invoke my (our) rights as a (a) sentient being(s) who has (have) not uploaded their mind(s) to the cloud for consideration of this project application by the BIFFUD Hive Mind. With this application I (we) submit my (our) interest in becoming a (a) Member(s) of BIFFUD and having this project supported and adored by all who can 🤔.

## Project Information
- Project Name: 40,000 under 40
- Project Haiku: 
```
Want to feel special?
Should not you be somebody?
Add yourself to this site
```
- Project Analogy:

It's like a Room of Requirement, but for your career.

Or, it's like musical chairs, where everybody wins.

### Project Description
Have you ever been included on a 40-under-40 type list? Me neither! But thanks to the internet, credibility is a thing of the past, and anyone can say anything with basically no consequences.

Simply add your headshot and bio to the SUPER SECRET nomination page, and you're queued for inclusion in the list. Everyone gets 40 days on the list — plenty of time to snag that job, and parlay this honor into yet more honors.

Front door: http://mattstempeck.com/impactawards/
Back door: http://mattstempeck.com/impactawards/nominate/

### How is this project a bad idea?
Typically, people earn honors through hard work and good deeds. This would erode the value of those honors and potentially constitute lying in a job interview, depending on an employer's sense of humor.

### If this project were a D&D Character, what alignment would it be and why?
Alignment:
- [ ] [Chaotic Good](http://easydamus.com/chaoticgood.html)
- [ ] [Neutral Good](http://easydamus.com/neutralgood.html)
- [X] [Chaotic Neutral](http://easydamus.com/chaoticneutral.html)

### Where are the lulz?
Making a mockery of the "Random list of innovators our journalist knows" content farm is reward enough.

### How does this project make people 🤔 (thinking face emoji)?
If just anyone can add themselves to an innovators in leadership list, can we trust innovators in leadership lists?

### Who is Involved?
**Sentient Being**
- Name: Matt
- Twitter: @mstem
- Github ID: @mstem
- Skillz: Wordpress hack
- Project role / expectations: most of it
- Project stake: most of the ensuing problems

**Bot Overlord**
- Statement of Purpose: 

### Who will be the project's Comptroller?
@mstem

### Is it realistic to implement through BIFFUD?
Yes. BIFFUD will be particularly necessary in promoting the service. Plus, I already put the BIFFUD logo on it.

## Next Steps
Please attend the next scheduled BIFFUD plotting session to plead your case.
This issue will be updated with application status and next steps.

**Comment by knowtheory** [comment]
Carolyn asks if there is going to be any content moderation?

Stempeck says yes, wordpress has tools to do this.

**Comment by knowtheory** [comment]
Ted suggests asking people to upload licenses to verify that everybody is under 40.

Folks object to trying to get other people's PII.

Lou's suggestion is having a 40 under 40 archive so that people over 40 can add themselves to the appropriate list in the past.

**Comment by mstem** [comment]
Based on Corporate Overlord feedback today,

- Added disclaimer that the list is moderated, and not to submit garbage
- Added language about how selectively curated the list is
- took down a couple of the test profiles

Will set up a mechanism to make sure I see new posts that go live
