### ISSUE TITLE
Budget Request: Branding and Website 

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/corporate#72]
## What do you want?
Funding to pay for a branding exercise and the professional design and implementation of a website.

Total cost: 3,000 EUR (aka $3,512.54 as of this moment.)
Breakdown: 1,000 for branding, 2,000 for the website

## When do you want it?
NOW!!!!!!

## What will happen to it after you die?
The results of this will live on forever at the Internet Archive.
I can also commit to printing out copies of the website once it is finished and putting it in a time capsule somewhere.

## What is the value proposition, return on investment, corporate synergistic alignment, disruption impact?  Will this move the needle, or amplify low hanging fruit?

We really need a website that we're comfortable sharing with random strangers on the street.  Specifically we want a digital brand and presence that accomplishes the following:

```
Makers -- we want people who make things to know about our organization and participate.

Foundations and funders -- we want foundations to feel comfortable funding us to create things, we want them to appreciate the VALUE of the culture we harbor and want to be associated with that culture.

Partners -- We want people who need things built to understand that we are capable creators; this might be organizations like the BBC or startups like Meedan who might hire us to develop products with a predefined scope of work.

Users -- We want potential users of the things we create to know what we're about and take joy in the fact that by using our stuff (or maybe some day paying for it) they are supporting something awesome (and they can be a part of it too)
```

## We are probably looking skeptical right now.  Any other considerations?

I'll take some of the money talk out of github, but I think this can be done in a sustainable way for the organization.

**Comment by mtigas** [comment]
> When do you want it?
> 
> NOW!!!!!!

sorry, the correct answer was [fry's dog](https://www.youtube.com/watch?v=WfgVdpAVtF8). please try your request again later

**Comment by slifty** [comment]
Shit you're right...

<s>but</s> plus if I edit this now it might create some kind of constitutional crisis<s>....</s>!
