### ISSUE TITLE
[Project Application] Montaging the Montage Montagery

### ISSUE THREAD

**Issue by maboa** [BadIdeaFactory/corporate#73]
# I HEREBY INVOKE MY RIGHTS...
As described in section 11.11.B of the BIFFUD Corporate Bylaws I hereby invoke
my rights as a sentient being who has not uploaded their mind to the cloud for consideration of this project application by the BIFFUD Hive Mind.  With this
application I submit my interest in becoming a Member of BIFFUD and having this
project supported and adored by all who can 🤔.

## Project Information
- Project Name: Montaging the Montage Montagery, aka Triple M, aka M and M and M, aka emineminem
- Project Haiku: Upon giving Bice some Grappa
He looked at me and asked politely
Do you like Frank Zappa?

- Project Analogy: It's like Scalextric for Video Facts

### Project Description

The goal is to easily allow video content to be annotated. We'll employ what we've learned working on Hyperaudio over the years to produce Interactive Transcripts that allow selections to be annotated / shared. 

This is a legacy system that we're trying to bring up to date. This will involve several challenges including:

1. Mixing React with Angular
2. Not touching the back-end

We will come together once a week to sing the following verse to Ed Bice:

One man one goal one mission,
One heart one soul just one solution,
One flash of light yeah one god one vision
One flesh one bone,
One true religion,
One voice one hope,
One real decision,
Wowowowo gimme one vision

### How is this project a bad idea?
Meedan's CEO Ed Bice is probably undercover FBI. His MO is to undermine BIF, we're on to him though. Ever noticed that BIF is an anagram of FBI? 

### If this project were a D&D Character, what alignment would it be and why?
Alignment (CHOOSE ONE):
- [Chaotic Neutral](http://easydamus.com/chaoticneutral.html)

Don't know? [This might help](https://www.google.com/search?q=D%26D+alignment+tables&source=lnms&tbm=isch)

### Where are the lulz?
In every nook and cranny that this project inhabits.

### How does this project make people thinking face emoji?
We have no idea what we're doing or working on. Also Angular.

### Who is involved?

- Name: Sir Mark of Boas
- Twitter: @maboa
- Github ID: maboa
- Skillz: Beastmastery and not living up to expectations.
- Project role / expectations: Beastmastery and not living up to expectations.
- Project stake: 25%
---

- Name: The Right Reverend Dan Schultz
- Twitter: @slifty 
- Github ID: slifty
- Skillz: Overlording
- Project role / expectations: Overlording us with his overlordery.
- Project stake:  25%
---

- Name: Group Captain Laurian Gridinoc
- Twitter: @gridinoc 
- Github ID: Laurian
- Skillz: Overengineering, Premature Optimisation, Choosing immature tech because shiny
- Project role / expectations: Vastly underestimating the project in hand, much procrastination
- Project stake:  25%
---

- Name: His Royal Highness the Piotr of Fedorczyk
- Twitter: @presentday
- Github ID: piotrf
- Skillz: Making things look good, making things easy to use, making things work
- Project role / expectations: Making things look good, less so making things easy to use, even less so making things work
- Project stake:  25%
---

### Who will be the project's Comptroller?
Sir Mark of Boas

### Is this realistic to implement via BIFFUD?
Sure. This is fine!

## Next Steps
1. Attend the next scheduled BIFFUD plotting session to plead your case.
2. Plan the work, do the work, reflect on the work, rinse and repeat until done.

### How (often) will you be providing updates to the organization?
Weekly on ze Slack machine

**Comment by slifty** [comment]
UPDATE: maboa is the comptroller for this one -- assuming he is willing!
