### ISSUE TITLE
Aunty Beeb + Narrative Text 

### ISSUE THREAD

**Issue by maboa** [BadIdeaFactory/corporate#74]
# I HEREBY INVOKE MY RIGHTS...
As described in section 11.11.B of the BIFFUD Corporate Bylaws I hereby invoke
my rights as a sentient being who has not uploaded their mind to the cloud for consideration of this project application by the BIFFUD Hive Mind.  With this
application I submit my interest in becoming a Member of BIFFUD and having this
project supported and adored by all who can 🤔.

## Project Information
- Project Name: [Narrative Text Things for BBC News Labs]
- Project Haiku: [5 / 7 / 5]
You scratch my back and
I'll report you to the appropriate authorities
Just kidding, I'll scratch yours

- Project Analogy: [It's like A defective Clockwork Orange for Basement Jaxx]

### Project Description
Well... previously we worked on automatic subtitling thing, this tine they need to add the ability to add Narrative Text to things - eg "The spider advances slowly towards the sleeping baby..."

### How is this project a bad idea?
There is no way the BBC (a steadfast British bastion of British Britishness) should employ such a young and anarchic organisation  such as BIFFUD to do anything .... and yet ...

### If this project were a D&D Character, what alignment would it be and why?
Alignment (CHOOSE ONE):
- Chaotic Bad - we're dancing with the devil on this one - and so are they!

### Where are the lulz?
British upper crust establishment vs BAD IDEA FACTORY! You tell me! The ground is ripe.

### How does this project make people thinking face emoji?
WTF are the BBC doing working with these losers!!!???

### Who is involved?

- Name: Markus Juanus Boasus
- Twitter: maboa
- Github ID: maboa
- Skillz: speaking english with an english accent
- Project role / expectations: PM (project mitigation)
- Project stake: 33

----

- Name: Laurianus Di Gridinocous
- Twitter: gridinoc
- Github ID: laurian
- Skillz: speaking english with a romanian accent
- Project role / expectations: making things, breaking things, blaming others
- Project stake: 33

---

- Name: Piotrudus Fedorczyckelious
- Twitter: PresentDay
- Github ID: piotrf
- Skillz: speaking english with a slight polish accent
- Project role / expectations: making things look better than they are
- Project stake: 33

### Who will be the project's Comptroller?
Markus Juanus Boasus

### Is this realistic to implement via BIFFUD?
Yes and no

## Next Steps
1. Attend the next scheduled BIFFUD plotting session to plead your case.
2. [List out your project plan here, in a series of steps]
- do the work
- get the moneys
- scarper

### How (often) will you be providing updates to the organization?
Upon request

**Comment by slifty** [comment]
I HAVE NO IDEA IF BRITISH PEOPLE CALL THE BBC AUNTY BEEB OR IF YOU ARE JUST TROLLING THE HELL OUT OF US.
