### ISSUE TITLE
Budget for basic accounting so lou doesn't go to jail

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/corporate#75]
## What do you want?
Now that we have projects involving money and are switching to accrual accounting, we need to actually actualize accurate accrual accounting.

Since we have SUPER SECRET CONNECTIONS we can get a discount on CLOUD ACCOUNTING SOFTWARE so it costs $25 a month.

That may sound like a lot but BOY is it a bargain.  How much of a bargain?  I'm pretty sure so much that I'm not allowed to tell you.  Anyway, please approve a $300 annual recurring expense so that we can afford to afford nice things.

## When do you want it?
Now.

## What will happen to it after you die?
The data will live on forever so that I can respond to IRS audits on BIFFUD's behalf for all eternety.

## What is the value proposition, return on investment, corporate synergistic alignment, disruption impact?  Will this move the needle, or amplify low hanging fruit?
Look, it's either this or an excel spreadsheet.

## We are probably looking skeptical right now.  Any other considerations?
We need this to be able to pay people money, including people like YOU.

## Next Steps
Please attend the next scheduled BIFFUD plotting session to plead your case.

**Comment by louh** [comment]
I would very much like to not go to jail please.

**Comment by maboa** [comment]
Before placing my vote - I think I need to know if Lou can do our accounts from jail. Isn't jail the natural habitat of the Treasure Goblin?
