### ISSUE TITLE
2018 Q4 Serious Bylaw Improvements

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/corporate#83]
Now that we are doing more serious bzns, it's time to review our bylaws.  Some concepts that I would like us to consider in an updated bylaw draft:

- Codify the 2.4% tithe on gross income for projects that go through BIFFUD; add some kind of clause around direct reimbursements (e.g. someone buys something that gets paid back directly by a client, we shouldn't take a tithe there).

- Update our title for "Minions" -- it was funny at the time, still is really, but it's also a little rude.  We think that "Accomplices" has a better ring to it while still implying participation in sinister and criminal plots.

- Add better structure around budget requests -- now that I've become an Official Certified Accountant* for the company, I've learned the errors in our ways.  We need budget requests to always have the following components: (1) the exact amount requested, (2) the term of the request {so when the money has to be spent by}, (3) what happens to leftover funds, (4) a description of what it means to have "bought" the thing {so we know when 3 takes effect}

- Require budgeting for petty cash fund.  Right now there is a loophole that Lou and I have Totally Not Abused So Far We Swear which would allow us to spend unlimited money in <$100 increments.  This isn't the intent of petty cash fund, and it makes it hard to hold us accountable.  We should require that the hive allocate money to petty cash, maybe with a recommended $200 at the beginning of the year.  This can be refreshed at a plotting session the same way any budget could be set.

- Add some language explaining the spirit of BIFFUD's money structure, with suggested guidelines for project owners as they think about budgets.  Basically, helping folks understand what kinds of resources they can expect BIFFUD corporate to pay for vs what they should expect to be paying on their own.

- Figure out how to handle the whole "we are kind of acting like an agency" thing.  We can't wait for the hive mind to approve each individual client project or grant application.  We need to figure out some kind of structure to support funded work.  This will likely involve some kind of faith in the Executive Overlord team when it comes to *FUNDED* projects

- Add in some concept for hibernation of projects.  Some projects we have approved aren't moving, which is OK and expected; we should figure out some way to indicate the live ones.

- Potentially build in an expectation that if we approve a project, we are committing to fund a petty cash fund for the project.  This will give some teeth and meaning to our approval, and support the project's success.  Right now it costs nothing to approve a project, and as a result I think we have more stagnant projects.

* I am not a certified accountant

**Comment by louh** [comment]
> Potentially build in an expectation that if we approve a project, we are committing to fund a petty cash fund for the project. This will give some teeth and meaning to our approval, and support the project's success. Right now it costs nothing to approve a project, and as a result I think we have more stagnant projects.

I approve of making this explicit. This would allow us to be more critical of approving projects and provide a much-needed basic cushion of flexibility and support for approved projects. Combined with a limited term for funding requests (see point 3), whereby the petty cash returns to the general fund, this essentially gives approved projects a soft deadline for completion (if they plan to use the money) or risk having to complete the project without the petty cash (subject to re-request and re-approval).

**Comment by maboa** [comment]
Late to the party - but just wanted to say that all sounds sensible. WHAT IS GOING ON?

**Comment by mstem** [comment]
These all sound entirely reasonable. Also, re:

"Add in some concept for hibernation of projects. Some projects we have
approved aren't moving, which is OK and expected; we should figure out some
way to indicate the live ones."

I have only two words: ZOMBIE DOME

**Comment by slifty** [comment]
I am like 99% sure that we made all these changes, so I'll close this one.
