### ISSUE TITLE
[Overlord Application] Fatima

### ISSUE THREAD

**Issue by sugaroverflow** [BadIdeaFactory/corporate#87]
## ➡ 👍 🎇 🤸🏾 🎐 📛 🖐🏿 🛎 🛀🏿 🚍 💇🏾 📆 🛀🏽 ♿ 🤸🏿

🤣 🖖 🙋🏻 🎈 👊🏻 🗂 🇹🇨 🛀 🙅🏿 🥑 ➿14.2.A 🤠 👊🏿 🚤 ♒ 👁‍🗨 👕 🤾🏾 ⏰ 🖍 🏡 🕳 💣 🤼🏼 💖 🤶🏾 🇸🇯 🤠 🇵🇪 🌥 😇 🇧🇩 🉑 👂🏻 ⛩ 🎨 🏖 🍽 👐🏼 👎 👃 😋 👮🏻 😗 🏃🏽 🇵🇦 🇬🇺 🇦🇬 🛅 🕵🏿 💪🏽 🌺 🤷🏻 🇲🇫 ✔ 🍡 👨🏻 🇨🇲 👸🏾 🐿 🇾🇪 👅 🌺 😚 🔆 👏🏼 👵 👲🏽 👻 💂 🚂 🙆🏽 🤦🏽 🌾 🍈 🤜🏿 ✊ 👜 🕞 🙏🏽 🇹🇲 🕵🏿 👶🏿 👩🏾 🇦🇱 🍻 🇨🇺 👵🏾 😄 ♥ ❇.  🇦🇽 👮🏾 ❕ 🕺🏼 🇮🇨 🏋 🇨🇷 🇰🇳 👩‍❤️‍💋‍👩 🖲 🌼 🈶 🎹 👏🏽 ⏫ 💝 🎅🏽 🈂 📠 🇱🇮 🤼🏾 👬 4️⃣ 🤜🏽 🗞 🕓 🔺 🏎 🎅🏿 🌞 Ⓜ 💟 🇵🇪  

🎬 🆚 🤙 👴🏿 ⏹ 🔝 🤚🏿 🕠 🕺🏽 😾 🤴🏽 🎰 📅 🗻 🙌🏻 ✍ 📫 🏠 💒 🔟 🇲🇻 🏠 👦 🛀🏽 👨‍👨‍👦‍👦 🕣 🇭🇺 🤝🏿 ⏳ 🐝 🚁 🚴🏼 🖐🏿 ☺ 🇹🇹 😮 🤶🏻 🤳🏽 🖊 ❔ 🤜🏽 🙋🏾 🔬 🤷 😝 🔵 ♒  

## Candidate Information
- Full Name*: 🎆 🅰️ 🎉 🍨 🎤 🅰️   ⭐️ 🅰️ 🐰 🅰️ 🎧    ⌨️ 🎧 🅰️ 😆 🍨 🗡 
- Twitter Handle: 💂🏼 🚶🏼 🇵🇫 🙋 🇨🇱 💇🏼
- Social Security Number (pick one): 1️⃣ 1️⃣ 2️⃣ 3️⃣ 5️⃣ 9️⃣ 7️⃣ 8️⃣ 9️⃣ 9️⃣

### What the title of your biography?
💂🏼 🚶🏼 🇵🇫 🙋 🇨🇱 💇🏼    🙍 🇱🇻 👀 💁🏿 ☠ 👰 🇸🇲 🚃 ☺ 🚾 🤽🏼 😁 🎸 👵 🛀🏻 👇🏿 ⛈ 🎲 😄 💁 🙌🏽 🐨 🙍🏿
### Ok, now write your biography?
👟 🌦 Ⓜ 👨🏻 🏃🏽 💙 🚵🏾 🇷🇪 🤓 🏥 😖 ⚽ 🇦🇮 🥙 👲🏻 🕘 💃🏾 🙄 🛋 🖕🏿 👌🏼 🔵 🇳🇺 🚞 🏎 🤕    🎅 😧 🇧🇿 👂🏻 🇦🇶 💪🏿 🚡 🉐 🎑! 📽 👂🏿 😊 🥖 👧🏽 👴🏽 👰 ☘ 🏃🏼 🏒 ☝🏻 🛄 🥃 👃🏽 👨🏻 🇦🇮 👸🏻 👂🏼 🏋🏾 ⚡ ▫ 💂🏽 👋🏿 🏊🏻 🔬 🤜🏿 🖊 🤶🏾 🔴 😟 🌟 🤘🏿 🇹🇲 👱🏾 👨‍👨‍👧‍👧 🚤 ⚱ 👌 🔩 🐘 👙 ⛹🏽 🤴🏼 🤡 🕌 👩‍👩‍👦 🏭   

### How will you submit your original creative work?
🖼 🎐 🌾 📭 📦 🖌 ⌚ 🇲🇳 🌿 👰🏿 🙍🏽 🇪🇪 👂🏽 👧 8️⃣. 

### Why do you want to be a Corporate Overlord?
🗳 🎤 🚪 🌪 👆🏻 🌈 🕺🏾 🏳 🇫🇷 👹 🛥 🍗 🔽 🤳🏽 🐻 💈 🇬🇲 👮🏽 💅🏿 🎾 👋🏼 🍤 🏊🏿 💃🏽 📂 🈺 🈴 👃 🍯 💁 🌳 🥑 🕋 🤾🏼 🚁 🇨🇷 👟 👳🏿   

### Do you identify as a cis-hetero white man?
- [X] 🤔

## Next Steps
✔️ see you Jan 20!

**Comment by slifty** [comment]
lolololololololololololol

**Comment by sugaroverflow** [comment]
P.S: it's not random emojis 😁

**Comment by slifty** [comment]
Our scientists have figured out the translation mechanism (though do not know the method by which you select the emoji so it is only one way)

----------

## Candidate Information
- Full Name*: fatimasatmakhalsd
- Twitter Handle: gwfrfh <-- that can't be right
- Social Security Number (pick one): 1️ 1️ 2️ 3️ 5️ 9️ 7️ 8️ 9️ 9️


## Bylaw Questions
### What the title of your biography?
💂🏼 🚶🏼 🇵🇫 🙋 🇨🇱 💇🏼    🙍 🇱🇻 👀 💁🏿 ☠ 👰 🇸🇲 🚃 ☺ 🚾 🤽🏼 😁 🎸 👵 🛀🏻 👇🏿 ⛈ 🎲 😄 💁 🙌🏽 🐨 🙍🏿
### Ok, now write your biography?
👟 🌦 Ⓜ 👨🏻 🏃🏽 💙 🚵🏾 🇷🇪 🤓 🏥 😖 ⚽ 🇦🇮 🥙 👲🏻 🕘 💃🏾 🙄 🛋 🖕🏿 👌🏼 🔵 🇳🇺 🚞 🏎 🤕    🎅 😧 🇧🇿 👂🏻 🇦🇶 💪🏿 🚡 🉐 🎑! 📽 👂🏿 😊 🥖 👧🏽 👴🏽 👰 ☘ 🏃🏼 🏒 ☝🏻 🛄 🥃 👃🏽 👨🏻 🇦🇮 👸🏻 👂🏼 🏋🏾 ⚡ ▫ 💂🏽 👋🏿 🏊🏻 🔬 🤜🏿 🖊 🤶🏾 🔴 😟 🌟 🤘🏿 🇹🇲 👱🏾 👨‍👨‍👧‍👧 🚤 ⚱ 👌 🔩 🐘 👙 ⛹🏽 🤴🏼 🤡 🕌 👩‍👩‍👦 🏭   

### How will you submit your original creative work?
🖼 🎐 🌾 📭 📦 🖌 ⌚ 🇲🇳 🌿 👰🏿 🙍🏽 🇪🇪 👂🏽 👧 8️⃣. 

## Survey
### Why do you want to be a Corporate Overlord?
🗳 🎤 🚪 🌪 👆🏻 🌈 🕺🏾 🏳 🇫🇷 👹 🛥 🍗 🔽 🤳🏽 🐻 💈 🇬🇲 👮🏽 💅🏿 🎾 👋🏼 🍤 🏊🏿 💃🏽 📂 🈺 🈴 👃 🍯 💁 🌳 🥑 🕋 🤾🏼 🚁 🇨🇷 👟 👳🏿

**Comment by sugaroverflow** [comment]
The Full Name field doesn't follow the rest of the emoji code. I hinted that with the asterisk :) That was just me playing with emojis and names before I found a better way to _encode_ emojis.

**Comment by sugaroverflow** [comment]
@slifty I suppose your scientists may have already figured this out, but it's not a 1:1 mapping of the alphabet. Observe: 

💂🏼 🚶🏼 🇵🇫 🙋 🇨🇱 💇🏼 = **sugaroverflow** 
😁 🦈 ⛪ 🏴 🇲🇽 🈚 🐟 = **sugaroverflows**

**Comment by sugaroverflow** [comment]
@slifty hahahaha, don't worry I caught a glimpse of the failure via the email notification. 

It's no fun if the worst can't make sense of it! Making it complex may have been a bad idea 😛 

Here's something simpler. The _key_ is the [glowing star](https://emojipedia.org/glowing-star/) emoji (since I'm a rising star). Best of luck! 

# 👔🐧😽😇🍋👔😇🚡 🗾🏂💸📝🚂🚕🚂🍱 😇🚕💓🎍💸🍋 💁💸💓💸🍋
---
 💸🗾 🚡😽🗾💁😇🚕🍬😽🚡 🚕🚂 🗾😽💁💓14.2.A 👔🔦 💓👨😽 🍬🚕🔦🔦🎍🚡 💁👔😇🏂👔😇💸💓😽 🍬👇🍋💸📝🗾 🚕 👨😽😇😽🍬👇 🚕🚂🐧👔🎸😽 😷👇 😇🚕🍱👨💓🗾 💸🗾 💸 🗾😽🚂💓🚕😽🚂💓 🍬😽🚕🚂🍱 📝👨👔 👨💸🗾 🚂👔💓 🎍🏂🍋👔💸🚡😽🚡. 📝🚕💓👨 💓👨🚕🗾 💸🏂🏂🍋🚕💁💸💓🚕👔🚂 🚕 🗾🎍🍬😷🚕💓 😷👇 🚕🚂💓😽😇😽🗾💓 🚕🚂 🍬😽💁👔😷🚕🚂🍱 💸 💁👔😇🏂👔😇💸

🚕 🎍🚂🚡😽😇🗾💓💸🚂🚡 💓👨💸💓 😷👇 💸🏂🏂🍋🚕💁💸💓🚕👔🚂 📝🚕🍋🍋 🚂👔💓 🍬😽 💁👔🚂🗾🚕🚡😽😇😽🚡 📝🚕💓👨👔🎍💓 💓👨😽 🗾🎍🍬😷🚕🗾🗾🚕👔🚂 👔🔦 💸🚂 👔😇🚕🍱🚕🚂

## Candidate Information
- Full Name: Fatima Sarah Khalid
- Twitter Handle: 🗾🎍🍱💸😇👔🐧😽😇🔦🍋👔📝
- Social Security Number (pick one): 112 359 7899

## Bylaw Questions
### What the title of your biography?
🗾🎍🍱💸😇👔🐧😽😇🔦🍋👔📝    👨👔📝 🗾👨😽 🍋🚕💓😽😇💸🍋🍋👇 🎸😽🏂💓 😽🐧😽😇👇💓👨🚕🚂🍱 🔦😇👔😷 🔦💸🍋🍋🚕🚂

### Ok, now write your biography?
😷👇 🚂💸😷😽 🚕🗾 🔦💸💓🚕😷💸 💸🚂🚡 🚕 💸😷 💸 🚡😽🐧😽🍋👔🏂😽😇 📝🚕💓👨 💁👔🚡! 👩 🍋👔🐧😽 📝👔😇🎸🚕🚂🍱 📝🚕💓👨 💓😽💁👨🚂👔🍋👔🍱👇 💸🚂🚡 🍬😽🍋🚕😽🐧😽 🗾💓😇👔🚂🍱🍋👇 🚕🚂 🍬🎍🚕🍋🚡🚕🚂🍱 😷👔😇😽 🚡🚕🐧😽😇🗾😽 💸🚂🚡 🚕🚂💁🍋🎍🗾🚕🐧😽 💓.


### How will you submit your original creative work?
🗾🍋🚕🚡😽 🚡😽💁🎸 🏂😇😽🗾😽🚂💓💸💓🚕👔🚂 🚕🚂 😷😽😽. 

## Survey
### Why do you want to be a Corporate Overlord?
🍬🚕🔦🔦🎍🚡 🚕🗾 💸 😇😽💸🍋🍋👇 💁👔👔🍋 🍬🎍🚂💁👨 👔🔦 🏂😽👔🏂🍋😽 💸🚂🚡 🚕 📝👔🎍🍋🚡 🍋👔🐧😽 💓👔 🍬😽 💸 🏂💸😇💓   

### Do you identify as a cis-hetero white man?
- [X] 🤔

## Next Steps
✔️ see you sunday!

---

If you figure it out this time, I demand some kind of advantage during my audition/plea/interview 😁

**Comment by boldenburg** [comment]
overlord spawning ritual catal

as described in sect14.2.A of the biffud corporate bylaws i hereby invoke my rights as a sentient being who has not uploaded. with this application i submit my interest in becoming a corpora



i understand that my application will not be considered without the submission of an origin



Candidate Information

Full Name: Fatima Sarah Khalid

Twitter Handle: sugaroverflow

Social Security Number (pick one): 112 359 7899

Bylaw Questions

What the title of your biography?

sugaroverflow how she literally kept everything from fallin



Ok, now write your biography?

my name is fatima and i am a developer with cod! 👩 love working with technology and believe strongly in building more diverse and inclusive t.



How will you submit your original creative work?

slide deck presentation in mee.



Survey

Why do you want to be a Corporate Overlord?

biffud is a really cool bunch of people and i would love to be a part

**Comment by knowtheory** [comment]
Can we close and accept this?  btw, in future can we make Overlord Applications pull requests to add them to our official registry?

**Comment by slifty** [comment]
Great call and good idea -- the only question is whether PRs are more technically challenging than opening an issue.  I'll defer to the group on that one / maybe we can ask @sugaroverflow and @boldenburg (Beastmaster / Secretary of Code)
